# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'colors.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Colors(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(628, 140)
        Form.setStyleSheet("background-color: rgb(38, 17, 0);\n"
"")
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(10, 20, 101, 21))
        self.label.setStyleSheet("font: 12pt \"MS Shell Dlg 2\";\n"
"background-color: rgb(253, 179, 255);")
        self.label.setObjectName("label")
        self.pushButton = QtWidgets.QPushButton(Form)
        self.pushButton.setGeometry(QtCore.QRect(10, 60, 75, 23))
        self.pushButton.setStyleSheet("background-color: rgb(178, 255, 249);")
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(Form)
        self.pushButton_2.setGeometry(QtCore.QRect(140, 60, 75, 23))
        self.pushButton_2.setStyleSheet("background-color: rgb(185, 250, 255);")
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_3 = QtWidgets.QPushButton(Form)
        self.pushButton_3.setGeometry(QtCore.QRect(280, 60, 75, 23))
        self.pushButton_3.setStyleSheet("background-color: rgb(188, 249, 255);")
        self.pushButton_3.setObjectName("pushButton_3")
        self.pushButton_4 = QtWidgets.QPushButton(Form)
        self.pushButton_4.setGeometry(QtCore.QRect(410, 60, 75, 23))
        self.pushButton_4.setStyleSheet("background-color: rgb(207, 255, 255);")
        self.pushButton_4.setObjectName("pushButton_4")
        self.pushButton_5 = QtWidgets.QPushButton(Form)
        self.pushButton_5.setGeometry(QtCore.QRect(540, 60, 75, 23))
        self.pushButton_5.setStyleSheet("background-color: rgb(192, 250, 255);")
        self.pushButton_5.setObjectName("pushButton_5")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label.setText(_translate("Form", "COLORS"))
        self.pushButton.setText(_translate("Form", "function1"))
        self.pushButton_2.setText(_translate("Form", "function 2"))
        self.pushButton_3.setText(_translate("Form", "function 3"))
        self.pushButton_4.setText(_translate("Form", "functoin 4"))
        self.pushButton_5.setText(_translate("Form", "functon 5"))
