# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'first_widget.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class First(object):
    def setupUi(self, Hello):
        Hello.setObjectName("Hello")
        Hello.resize(671, 448)
        Hello.setStyleSheet("background-color: rgb(26, 10, 0);")
        self.verticalLayoutWidget = QtWidgets.QWidget(Hello)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(210, 150, 211, 121))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.pushButton = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.pushButton.setStyleSheet("font: 16pt \"MS Shell Dlg 2\";\n"
"font: 16pt \"MS Shell Dlg 2\";\n"
"background-color: rgb(246, 199, 255);")
        self.pushButton.setObjectName("pushButton")
        self.verticalLayout.addWidget(self.pushButton)
        self.label = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label.setStyleSheet("font: 10pt \"MS Shell Dlg 2\";\n"
"font: 12pt \"MS Shell Dlg 2\";\n"
"background-color: rgb(255, 208, 255);")
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.lineEdit = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.lineEdit.setStyleSheet("background-color: rgb(255, 210, 255);")
        self.lineEdit.setObjectName("lineEdit")
        self.verticalLayout.addWidget(self.lineEdit)
        self.horizontalLayoutWidget = QtWidgets.QWidget(Hello)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(40, 10, 561, 41))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.pushButton_4 = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.pushButton_4.setStyleSheet("background-color: rgb(226, 250, 255);")
        self.pushButton_4.setObjectName("pushButton_4")
        self.horizontalLayout.addWidget(self.pushButton_4)
        self.pushButton_3 = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.pushButton_3.setStyleSheet("background-color: rgb(213, 253, 255);")
        self.pushButton_3.setObjectName("pushButton_3")
        self.horizontalLayout.addWidget(self.pushButton_3)

        self.retranslateUi(Hello)
        QtCore.QMetaObject.connectSlotsByName(Hello)

    def retranslateUi(self, Hello):
        _translate = QtCore.QCoreApplication.translate
        Hello.setWindowTitle(_translate("Hello", "Form"))
        self.pushButton.setText(_translate("Hello", "START"))
        self.label.setText(_translate("Hello", "Enter your name:"))
        self.pushButton_4.setText(_translate("Hello", "HISTORY"))
        self.pushButton_3.setText(_translate("Hello", "HELP"))
